netapp/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views
from .views import (
    posts_of_following_profiles,
    like_unlike_post,
    invites_received_view,
    invite_profiles_list_view,
    send_invitation,
    remove_friends,
    accept_invitation,
    reject_invitation,
    search_view,
    post_comment_create_view,
    login_view,
    logout_view,
    register,


    ProfileDetailView,
    PostDeleteView,
    PostUpdateView,
    ProfileListView,
    #EditProfileView,
)


urlpatterns = [
    path("", ProfileListView.as_view(), name="all-profiles-view"),
    path("posts/", views.post_comment_create_view, name="posts"),
    path("posts-follow/", posts_of_following_profiles, name="posts-follow"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("liked/", like_unlike_post, name="like-post-view"),
    path("<pk>/delete", PostDeleteView.as_view(), name="post-delete"),
    path("<pk>/update", PostUpdateView.as_view(), name="post-update"),
    path("invites/", invites_received_view, name="invites-view"),
    path("send-invite/", send_invitation, name="send-invite"),
    path("remove-friend/", remove_friends, name="remove-friend"),
    path("invites/accept/", accept_invitation, name="accept-invite"),
    path("invites/reject/", reject_invitation, name="reject-invite"),
    path("to-invite/", invite_profiles_list_view, name='invite-profiles-view'),
    path("search/", views.search_view, name='search-view'),
    path("<slug>", ProfileDetailView.as_view(), name="profile-view"),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

network/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("netapp.urls")),
]

netapp/models.py
from django.contrib.auth.models import User
from django.core import validators
from django.db import models
from itertools import chain
import random
from django.db.models.aggregates import Max
from django.shortcuts import reverse

from django.db.models.deletion import CASCADE
from .utils import get_random_code
from django.template.defaultfilters import slugify
from django.core.validators import FileExtensionValidator
from django.db.models import Q


class ProfileManager(models.Manager):

    def get_all_profiles_to_invite(self, sender):
        profiles = Profile.objects.all().exclude(user=sender)
        profile = Profile.objects.get(user=sender)
        qs = Relationship.objects.filter(
            Q(sender=profile) | Q(receiver=profile))

        accepted = set([])
        for rel in qs:
            if rel.status == 'accepted':
                accepted.add(rel.receiver)
                accepted.add(rel.sender)
        print(accepted)

        available = [
            profile for profile in profiles if profile not in accepted]

        return available

    def get_all_profiles(self, me):
        profiles = Profile.objects.all().exclude(user=me)
        return profiles


class Profile(models.Model):
    first_name = models.CharField(max_length=64, blank=True)
    last_name = models.CharField(max_length=64, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    country = models.CharField(max_length=64, blank=True)
    avatar = models.ImageField(upload_to='avatars', default='avatar.png')
    background = models.ImageField(
        upload_to='backgrounds', default='background.png')
    following = models.ManyToManyField(
        User, related_name='following', blank=True)
    bio = models.TextField(default="No Bio..")
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(unique=True, blank=True)

    objects = ProfileManager()

    def __str__(self):
        return f"{self.user.username}"

    def get_absolute_url(self):
        return reverse("profile-view", kwargs={"slug": self.slug})

    __initial_first_name = None
    __initial_last_name = None

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.__initial_first_name = self.first_name
        self.__initial_last_name = self.last_name

    def save(self, *args, **kwargs):
        ex = False
        to_slug = self.slug
        if self.first_name != self.__initial_first_name or self.last_name != self.__initial_last_name or self.slug == "":
            if self.first_name and self.last_name:
                to_slug = slugify(str(self.first_name) +
                                  " " + str(self.last_name))
                ex = Profile.objects.filter(slug=to_slug).exists()
                while ex:
                    to_slug = slugify(to_slug + " " + str(get_random_code()))
                    ex = Profile.objects.filter(slug=to_slug).exists()
            else:
                to_slug = str(self.user)
        self.slug = to_slug
        super().save(*args, **kwargs)

    def get_followers(self):
        return self.following.all()

    def get_followers_num(self):
        return self.following.all().count()

    def get_my_posts(self):
        return self.post_set.all()

    def get_country(self):
        return self.post_set.all()

    def get_following_users(self):
        following_list = [p for p in self.get_following()]
        return following_list

    def get_followers_users(self):
        following_list = [p for p in self.get_followers()]
        return following_list

    def get_all_posts(self):
        users = [user for user in self.get_following()]
        posts = []
        qs = None
        for u in users:
            p = Profile.objects.get(user=u)
            p_posts = p.post_set.all()
            posts.append(p_posts)
        my_posts = self.post_set.all()
        posts.append(my_posts)
        if len(posts) > 0:
            qs = sorted(chain(*posts), reverse=True,
                        key=lambda obj: obj.created)
        return qs

    def get_posts_num(self):
        return self.post_set.all().count()

    def get_all_authors_posts(self):
        return self.post_set.all()

    def get_likes_given_num(self):
        likes = self.like_set.all()
        total_liked = 0
        for item in likes:
            if item.value == 'Like':
                total_liked += 1
        return total_liked

    def get_likes_received_num(self):
        posts = self.post_set.all()
        total_liked = 0
        for item in posts:
            total_liked += item.all().count()
        return total_liked

    def get_proposals_for_following(self):
        profiles = Profile.objects.all().exclude(user=self.user)
        followers_list = [p for p in self.get_following()]
        available = [p.user for p in profiles if p.user not in followers_list]
        random.shuffle(available)
        return available[:3]


STATUS_CHOICES = (
    ('send', 'send'),
    ('accepted', 'accepted')
)


class RelationshipManager(models.Manager):
    def invitations_received(self, receiver):
        qs = Relationship.objects.filter(receiver=receiver, status='send')
        return qs


class Relationship(models.Model):
    sender = models.ForeignKey(
        Profile, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(
        Profile, on_delete=models.CASCADE, related_name='receiver')
    status = models.CharField(max_length=8, choices=STATUS_CHOICES)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    objects = RelationshipManager()

    def __str__(self):
        return f"{self.sender}-{self.receiver}-{self.status}"


class Post(models.Model):
    # id is created automatically by Django
    picture = models.ImageField(upload_to='images', blank=True, validators=[
                                FileExtensionValidator(['png', 'jpg', 'jpeg'])])
    content = models.TextField()
    liked = models.ManyToManyField(Profile, blank=True, related_name="likes")
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return str(self.content[:20])

    def num_likes(self):
        return self.liked.all().count()

    @property
    def like_count(self):
        return self.liked.all().count()

    def get_user_liked(self, user):
        pass

    # Number of comments
    def num_comments(self):
        return self.comment_set.all.count()


class Comment(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    body = models.TextField(max_length=250)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.pk)


LIKE_CHOICES = (
    ('Like', 'Like'),
    ('Unlike', 'Unlike'),
)


class Like(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    value = models.CharField(choices=LIKE_CHOICES, max_length=8)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user}-{self.post}-{self.value}"

    def like_numb(self):
        return self.like.all().count()

netapp/forms.py
from django import forms
from .models import Profile, Post, Comment

class ProfileModelForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('first_name', 'last_name', 'bio', 'avatar')


class PostModelForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={'rows':2, 'cols': 30}))
    class Meta:
        model = Post
        fields = ('content', 'picture')


class CommentModelForm(forms.ModelForm):
    body = forms.CharField(label='', widget=forms.TextInput(attrs={'placeholder': 'Add a comment...', 'class':'comment'}))
    class Meta:
        model = Comment
        fields = ('body',)

netapp/templates/netapp/confirmDelete.html
{% extends "netapp/layout.html" %}

{% block title %}
    Delete Post
{% endblock title %}

{% block body %}
    {% if messages %}
        {% for message in messages %}
            {% if 'warning' in message.tags %}
                <div>
                    <div class="alert alert-warning" role="alert">
                        {{message}}
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}

    {% if not messages %}
            <div class="card center" style="width: 30rem;">
                <h3>Delete post?</h3>
                <form action="" method="POST">
                    {% csrf_token %}
                    <p>Are you sure you want to delete the post?s</p>
                    <button type="submit">Delete</button>
                </form>
            </div>
    {% endif %}
{% endblock body %}

netapp/templates/netapp/followers_posts.html
{% extends "netapp/layout.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load humanize %}

{% block title %}
    My Posts
{% endblock title %}

{% block body %}
<div>
    <div class="listfollow mt-5 mr-5 float-right">
        <h2>You follow:</h2>
        {% for p in profile.following.all %}
            <li>{{p}}</li>
        {% endfor %}
    </div>
    <div class="border border-light rounded" style="width: 20rem;">
        {% if post_added %}
            <div id="alertFade" class="alert alert-success" role="alert">Post added!</div>
        {% endif %}
        <form action="" method="POST" enctype="multipart/form-data" class="form-group post-form">
            {% csrf_token %}
            {{p_form}}
            <button type="submit" class="btn btn-sm btn-success" name="submit_pForm">Send Post</button>
        </form>
    </div>
    {% for obj in post_list %}
        <div class="card center" style="width: 30rem;">
            <div class="card-head" style="background-color: #d0e2bc;">
                <img width="50px" class="avatar img-thumbnail rounded-circle z-depth-2 ml-1" src={{obj.author.avatar.url}}> <a href="{% url 'profile-view' obj.author.slug %}">{{ obj.author.user }}</a> - {{ obj.created|naturaltime }}
                {% if request.user == obj.author.user %}
                    <a href="{% url 'post-delete' obj.pk %}"><button class="btn btn-sm btn-success float-right mt-2 mr-1">Delete</button></a>
                    <a href="{% url 'post-update' obj.pk %}"><button class="btn btn-sm btn-success float-right mr-1 mt-2">Edit</button></a>
                {% endif %}
            </div>
            <div class="card-body">
                {% if obj.picture %}
                    <img class="card-img" src="{{obj.picture.url}}">
                {% endif %}
                <hr>
                <span class="card-text">{{obj.content|safe}}</span>
            </div>
            <button class="cmt_btn ui button mb-5">show / hide comments</button>
            <div class="comment-box">
            {% if obj.comment_set.all %}
                {% for c in obj.comment_set.all %}

                    <img width="20px" class="avatar img-thumbnail rounded-circle"src={{c.user.avatar.url}} alt="">
                    <span>{{ c.user }}</span>
                    <div class="mt-2">{{ c.body }}</div>

                {% endfor %}
            {% endif %}
            </div>
            <div>
                <form action="" method="POST" class="form-group text-center">
                    {% csrf_token %}
                    <input type="hidden" name="post_id" value={{obj.id}}>
                    {{ c_form }}
                    <br>
                    <button type="submit" class="btn btn-success btn-sm mt-3 float-left ml-2" name="submit_cForm">Comment</button>
                </form>
                <form action="{% url 'like-post-view' %}" method="POST" id="{{obj.id}}" class="mt-0 like-form form-group float-right">
                    {% csrf_token %}
                    <input type="hidden" name='post_id' value={{obj.id}}>
                    <button type="submit" class="btn btn-sm btn-primary mt-0 mr-2 float-right like-btn{{obj.id}}">
                        {% if profile not in obj.liked.all %}
                            Like
                        {% else %}
                            Unlike
                        {% endif %}
                    </button>
                </form>
                <div class="float-right mr-2 mt-1 like-count{{obj.id}}">{{obj.like_count}}</div>
            </div>
        </div>
{% endfor %}

<div class="d-flex justify-content-center">
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            {% if post_list.has_previous %}
                <li class="page-item"><a class="page-link" href="?page=1">&laquo; First</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ post_list.previous_page_number }}">Previous</a></li>
            {% endif %}

            <li class="page-item disabled"><a class="page-link" href="#">Page {{ post_list.number }} of {{ post_list.paginator.num_pages }}</a></li>

            {% if post_list.has_next%}
                <li class="page-item"><a class="page-link" href="?page={{ post_list.next_page_number }}">Next</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ post_list.paginator.num_pages }}">Last &raquo</a></li>
            {% endif %}
        </ul>
    </nav>
</div>
</div>
{% endblock %}

netapp/templates/netapp/invites.html
{% extends "netapp/layout.html" %}

{% block title %}
    My invites
{% endblock title %}

{% block body %}

    {% if is_empty %}
        <h1 style="color:cyan;" class="text-center">No requests received..</h1>
    {% endif %}

    {% for obj in qs %}
    <div class="row d-flex justify-content-center">
        <div class="col-sm-5 grid">
            <div class="card container">
                <div class="row">
                    <div class="card-body col-2">
                        <img width="100px" class="avatar img-thumbnail rounded-circle z-depth-2 mt-4 ml-1" src={{obj.avatar.url}}>
                    </div>
                    <div class="col-5">
                        <h3>{{obj.user}}</h3>
                        <p>{{obj.bio}}</p>
                        <a href="">
                            <button class="btn btn-sm btn-primary mb-2 w-btn">See profile</button>
                        </a>
                        <form action="{% url 'accept-invite' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value={{obj.pk}}>
                            <button type="submit" class="btn btn-sm btn-outline-success w-btn"><i class="bi-check-lg"></i>&nbsp;Accept</button>
                        </form>
                        <form action="{% url 'reject-invite' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value={{obj.pk}}>
                            <button type="submit" class="btn btn-sm btn-outline-danger w-btn"><i class="bi-x-lg"></i>&nbsp;Reject</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}

{% endblock body %}

netapp/templates/netapp/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Social Network{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
        <link href="{% static 'static/styles.css' %}" rel="stylesheet">
        <link rel="icon" href="{% static 'static/icon.jpg' %}">
        <link href="https://fonts.googleapis.com/css?family=Archivo+Black&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Archivo:700&display=swap" rel="stylesheet">
        <!-- jquery -->
        {% block scripts %}
        <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
        <script src="{% static 'static/script.js' %}" defer></script>
        {% endblock scripts %}
    </head>
    <body>

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'all-profiles-view' %}">Network</a>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'profile-view' user.profile.slug %}"><strong>{{ user.username }}</strong></a>
                    </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link " href="{% url 'posts' %}">All Posts</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'posts-follow' %}">Following</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'invites-view' %}">Requests</a>
                    </li>
                    <form class="form-inline my-2 my-lg-0" method="POST" action="{% url 'search-view' %}">
                        {% csrf_token %}
                        <input class="form-control mr-sm-2" type="search" placeholder="Search Profiles" aria-label="Search" name="searched">
                        <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Search</button>
                    </form>
                    <li class="nav-item">
                        <a class="nav-link " href="{% url 'logout' %}">Log Out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'register' %}">Register</a>
                    </li>
                {% endif %}
                </ul>
            </div>
          </nav>

        <div class="container-fluid mt-3">
            {% block body %}
            {% endblock %}
            <div class="loader-wrapper">
                <span class="loader"><span class="loader-inner"></span></span>
            </div>
        </div>
        <footer class="page-footer footer">
            <div class="row pt-5">
                <div class="cold-md-12">
                    <div class="border-top ml-4" style="color: #f8f9fa;">
                        <p>Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This Website is Developed by <a id="social-link" class="blink_me" target="_blank" href="https://www.linkedin.com/in/khaledbenyahya/">Khaled Ben Yahya</a></p>
                    </div>
                </div>
            </div>
        </footer>
    </body>

</html>

netapp/templates/netapp/login.html
{% extends "netapp/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'login' %}" method="post" autocomplete="off">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    <h6>Don't have an account?</h6> <a href="{% url 'register' %}">Register here.</a>

{% endblock %}

netapp/templates/netapp/posts.html
{% extends "netapp/layout.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load humanize %}

{% block title %}
    My Posts
{% endblock title %}

{% block body %}
<div>
    <div class="border border-light rounded" style="width: 20rem;">
        {% if post_added %}
            <div id="alertFade" class="alert alert-success" role="alert">Post added!</div>
        {% endif %}
        <form action="" method="POST" enctype="multipart/form-data" class="form-group post-form dropzone">
            {% csrf_token %}
            {{p_form.as_p}}
            <button type="submit" class="btn btn-sm btn-success" name="submit_pForm">Send Post</button>
        </form>
    </div>
    {% for obj in post_list %}
        <div class="card center post" style="width: 30rem;">
            <div class="card-head" style="background-color: #d0e2bc;">
                <img width="50px" class="avatar img-thumbnail rounded-circle z-depth-2 ml-1" src={{obj.author.avatar.url}}> <a href="{% url 'profile-view' obj.author.slug %}">{{ obj.author.user }}</a> - {{ obj.created|naturaltime }}
                {% if request.user == obj.author.user %}
                    <a href="{% url 'post-delete' obj.pk %}"><button class="btn btn-sm btn-success float-right mt-2 mr-1">Delete</button></a>
                    <a href="{% url 'post-update' obj.pk %}"><button class="btn btn-sm btn-success float-right mr-1 mt-2">Edit</button></a>
                {% endif %}
            </div>
            <div class="card-body">
                {% if obj.picture %}
                    <img class="card-img" src="{{obj.picture.url}}">
                    <hr>
                {% endif %}
                <span class="card-text">{{obj.content|safe}}</span>
            </div>
            <button class="cmt_btn ui button mb-5">Show/Hide Comments</button>
            <div class="comment-box">
            {% if obj.comment_set.all %}
                {% for c in obj.comment_set.all %}

                    <img width="20px" class="avatar img-thumbnail rounded-circle"src={{c.user.avatar.url}} alt="">
                    <span>{{ c.user }}</span>
                    <div class="mt-2">{{ c.body }}</div>

                {% endfor %}
            {% endif %}
            </div>
            <div>

            </div>
            <div>
                <form action="" method="POST" class="form-group text-center">
                    {% csrf_token %}
                    <input type="hidden" name="post_id" value={{obj.id}}>
                    {{ c_form }}
                    <br>
                    <button type="submit" class="btn btn-success btn-sm mt-3 float-left ml-2" name="submit_cForm">Comment</button>
                </form>
                <form action="{% url 'like-post-view' %}" method="POST" id="{{obj.id}}" class="mt-0 like-form form-group float-right">
                    {% csrf_token %}
                    <input type="hidden" name='post_id' value={{obj.id}}>
                    <button type="submit" class="btn btn-sm btn-primary mt-0 mr-2 float-right like-btn{{obj.id}}">
                        {% if profile not in obj.liked.all %}
                            Like
                        {% else %}
                            Unlike
                        {% endif %}
                    </button>
                </form>
                <div class="float-right mr-2 mt-1 like-count{{obj.id}}">{{obj.like_count}}</div>
            </div>
        </div>
{% endfor %}

<div class="d-flex justify-content-center">
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            {% if post_list.has_previous %}
                <li class="page-item"><a class="page-link" href="?page=1">&laquo; First</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ post_list.previous_page_number }}">Previous</a></li>
            {% endif %}

            <li class="page-item disabled"><a class="page-link" href="#">Page {{ post_list.number }} of {{ post_list.paginator.num_pages }}</a></li>

            {% if post_list.has_next%}
                <li class="page-item"><a class="page-link" href="?page={{ post_list.next_page_number }}">Next</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ post_list.paginator.num_pages }}">Last &raquo</a></li>
            {% endif %}
        </ul>
    </nav>
</div>
{% endblock %}

netapp/templates/netapp/profile_list.html
{% extends "netapp/layout.html" %}

{% block title %}
    All Profiles
{% endblock title %}

{% block body %}
    {% if is_empty %}
        <h1>Currently..No profiles to interact with</h1>
    {% endif %}

    <h6>Follow some people you may know..</h6>

    {% for obj in profile_list %}
        <div class="row d-flex justify-content-center">
            <div class="col-sm-5 grid">
                <div class="card container">
                    <div class="row">
                        <div class="card-body col-2">
                            <img width="100px" class="avatar img-thumbnail rounded-circle z-depth-2 mt-4 ml-1" src={{obj.avatar.url}}>
                        </div>
                        <div class="col-5">
                            <h3>{{obj.user}}</h3>
                            <p>{{obj.bio}}</p>
                            <a href={{obj.get_absolute_url}}><button class="btn btn-sm btn-primary mb-2 w-btn">See profile</button></a>
                            <br>
                            {% if obj.user not in rel_receiver and obj.user not in rel_sender %}
                                <form action="{% url 'send-invite' %}" method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" name="profile_pk" value={{obj.pk}}>
                                    <button type="submit" class=" btn btn-sm btn-success w-btn"><i class="bi-plus-lg"></i>&nbsp;Follow</button>
                                </form>
                            {% endif %}

                            {% if obj.user in rel_receiver and request.user not in obj.following.all %}
                                <button class="btn btn-sm disabled "><i class="bi-three-dots"></i>&nbsp;Waiting aprroval</button>
                            {% endif %}

                            {% if request.user in obj.following.all %}
                                <form action="{% url 'remove-friend' %}" method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" name="profile_pk" value={{obj.pk}}>
                                    <button type="submit" class=" btn btn-sm btn-dark w-btn"><i class="bi-dash-lg"></i>&nbsp;Unfollow</button>
                                </form>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock body %}

netapp/templates/netapp/register.html
{% extends "netapp/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'register' %}" method="post" autocomplete="off">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    <h6>Already have an account?</h6> <a href="{% url 'login' %}">Log In here.</a>

{% endblock %}

netapp/templates/netapp/search.html
{% extends "netapp/layout.html" %}
{% load static %}

{% block title %}
    Searching
{% endblock title %}

{% block body %}
{% if searched %}
<h1 style="color: white;">You Searched For {{ searched }}</h1>
<br>
<table class="table table-dark table-responsive{-sm|-md|-lg|-xl} table-hover table-striped">
    <thead>
        <tr>
          <th scope="col">Profile</th>
          <th scope="col">Country</th>
          <th scope="col">Created</th>
        </tr>
    </thead>
    {% for p in profiles %}
      <tbody>
        <tr>
          <td><a href="{% url 'profile-view' p.slug %}">{{ p }}</a></td>
          <td>{{ p.country }}</td>
          <td>{{ p.created }}</td>
        </tr>
      </tbody>
    {% endfor %}
    {% else %}
    <h1 style="color: white;">You Forgot To Search For A Profile...</h1>
    {% endif %}
</table>


{% endblock body %}

netapp/templates/netapp/to_invite_list.html
{% extends "netapp/layout.html" %}

{% block title %}
    Invite Friends
{% endblock title %}

{% block body %}
    <ul>
        {% for item in qs %}
            <li style="color:white;">{{item}}</li>
        {% endfor %}
    </ul>
{% endblock body %}